version: '3.1'

services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    env_file:
      - ./.env

  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - 1234:1234
    environment:
      - HOST=0.0.0.0
